DRIVER_CONTROLLER_PORT = 1
OPERATOR_CONTROLLER_PORT = 0

GYRO_ID = 2

# Front Right Swerve Module
FR_DRIVE_MOTOR_ID = 6
FR_STEER_MOTOR_ID = 1
FR_CAN_CODER_ID = 4
FR_OFFSET = 145.898

# Front Left Swerve Module
FL_DRIVE_MOTOR_ID = 2
FL_STEER_MOTOR_ID = 8
FL_CAN_CODER_ID = 3
FL_OFFSET = 171.211

# Back Right Swerve Module
BR_DRIVE_MOTOR_ID = 10
BR_STEER_MOTOR_ID = 9
BR_CAN_CODER_ID = 5
BR_OFFSET = 237.568

# Back Left Swerve Module
BL_DRIVE_MOTOR_ID = 12
BL_STEER_MOTOR_ID = 7
BL_CAN_CODER_ID = 11
BL_OFFSET = 212.432
